# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YiWuHRSS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YiWuHRSS
	
    pod 'AMapSearch'
    pod 'AMapLocation'
    pod 'AMapNavi'
    pod 'AMap3DMap','4.6.1'
    

end
